import {
    ArrowDown,
    ArrowRight,
    Bot,
    Briefcase,
    Check,
    Code,
    Code2,
    Download,
    ExternalLink,
    FileCode,
    Flower,
    GitBranch,
    Github,
    GraduationCap,
    Image,
    Layers,
    LayoutDashboard,
    Link,
    Linkedin,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Paintbrush,
    RotateCw,
    Send,
    ShieldCheck,
    Smartphone,
    X,
} from 'lucide-react';
import type { SVGProps } from 'react';

const icons = {
  github: Github,
  linkedin: Linkedin,
  gitlab: GitBranch,
  menu: Menu,
  close: X,
  whatsapp: MessageCircle,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  externalLink: ExternalLink,
  download: Download,
  message: MessageCircle,
  send: Send,
  codeBox: Code2,
  code: Code,
  brush: Paintbrush,
  paintbrush: Paintbrush,
  refresh: RotateCw,
  smartphone: Smartphone,
  gitBranch: GitBranch,
  shield: ShieldCheck,
  robot: Bot,
  check: Check,
  react: Code2,
  layout: LayoutDashboard,
  link: Link,
  fileCode: FileCode,
  layers: Layers,
  mail: Mail,
  mapPin: MapPin,
  briefcase: Briefcase,
  graduation: GraduationCap,
  html5: FileCode,
  javascript: Code,
  apps: Layers,
  image: Image,
  flower: Flower,
};

type IconName = keyof typeof icons;

export function Icon({ name, className, ...props }: { name: IconName } & SVGProps<SVGSVGElement>) {
  const Component = icons[name];
  return <Component className={className} {...props} />;
}
